### ISSUE TITLE
When Upload button is pressed, the SPA shall open a system file picker.

### ISSUE THREAD

**Issue by s1ckret** [S1ckret-Labs/family-archive-spa#4]
The `SPA` shall `accept directories and the next MIME types`.

- image/jpeg
- image/gif
- image/png
- image/webp
- video/x-msvideo
- video/h264
- video/x-m4v
- video/mpeg
- video/mp4
- video/ogg
- video/webm

**Comment by G2p1** [comment]
While developing the download button, the selection of files with these types was also made, so it was implemented.
